### ISSUE TITLE
GitRelease without ChangoLog fail!

### ISSUE THREAD

**Issue by ricaun** [ricaun-io/ricaun.Nuke#51]
```
 Error: Target "GitRelease" has thrown an exception
  00:50:54 [ERR] Target GitRelease has thrown an exception
  System.ArgumentException: Expected object of type 'Nuke.Common.IO.AbsolutePath' to be not null (Parameter 'left')
     at Nuke.Common.IO.AbsolutePath.op_Division(AbsolutePath left, String right) in /_/source/Nuke.Common/IO/AbsolutePath.cs:line 79
     at ricaun.Nuke.Components.IHazChangelog.GetChangelogFile()
     at ricaun.Nuke.Components.IHazChangelog.GetReleaseNotes()
     at ricaun.Nuke.Components.IGitRelease.<get_GitRelease>b__1_6()
     at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
     at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

**Comment by ricaun** [comment]
Added `if (parent is null) return null;`
